# Generated by Django 4.2.30 on 2026-06-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='', help_text='支持 JPEG/PNG/GIF/WebP，最大 2MB', upload_to='avatars/', verbose_name='头像'),
        ),
    ]
